# .streamlit/config.toml

[server]
# Render sets the $PORT environment variable automatically
port = $PORT
headless = true
enableCORS = false

# Optional: default browser mode
browser.serverAddress = "0.0.0.0"

# Optional: hide the Streamlit header and menu for a cleaner look
[theme]
primaryColor="#4B88A2"
backgroundColor="#F5F5F5"
secondaryBackgroundColor="#EAEAEA"
textColor="#333333"
font="sans serif"

[runner]
# Limit memory usage if needed
# maxMemoryMB = 1024